name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Sonar Code Analysis
        env:
         GITHUB_TOKEN: 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
         SONAR_TOKEN: 2f76c0dcc5ea23690acec4f878af6ac8b872fd03
         SONAR_KEY: JohnnyKamigashima_Pascoa137
        run: |
                 mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                   -Dsonar.projectKey=JohnnyKamigashima_Pascoa137
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit
          java-version: 11